DROP SCHEMA IF EXISTS RECETAS;
CREATE SCHEMA RECETAS; 
USE RECETAS;

CREATE TABLE CATEGORIA (
	ID_CATEGORIA INT,
    NOMBRE VARCHAR(15) NOT NULL,
    PRIMARY KEY(ID_CATEGORIA)
);


CREATE TABLE RECETA (
	ID_RECETA INT,
    NOMBRE VARCHAR(15) NOT NULL,
    TIEMPO INT NOT NULL,
    DIFICULTAD VARCHAR(15) NOT NULL,
    ID_CATEGORIA INT,
	PRIMARY KEY(ID_RECETA),
    FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)

   
);

CREATE TABLE INGREDIENTE (
	ID_INGREDIENTE INT,
    NOMBRE VARCHAR(15) NOT NULL,
    CANTIDAD INT NOT NULL,
    UNIDAD VARCHAR(15) NOT NULL,
    ID_RECETA INT,
	PRIMARY KEY(ID_INGREDIENTE),
    FOREIGN KEY(ID_RECETA) REFERENCES RECETA(ID_RECETA)

   
);

CREATE TABLE PASO (
	ID_PASO INT,
    NUMERO INT NOT NULL,
    DESCRIPCION VARCHAR(100),
    ID_RECETA INT,
	PRIMARY KEY(ID_PASO),
    FOREIGN KEY(ID_RECETA) REFERENCES RECETA(ID_RECETA)
);


